services:
#  databaseservice:
#    image: databaseservice
#    build:
#      context: .
#      dockerfile: DatabaseService/Dockerfile
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - "5434:5432"
    restart: always

volumes:
  pgdata: